---
## This playbook deploys the whole application stack in this site.

- name: Deploy RDS Infratructure
  hosts: localhost
  connection: local
  # become: yes
  # become_method: su
  remote_user: root
  gather_facts: false
  vars:

# Global AWS Variables
    region: eu-west-1
    aws_network_name: dev

 # VPC Variables
    vpc_cidr: 10.5.0.0/16
    public_subnet_1_cidr: 10.5.1.0/24
    public_subnet_1_az: eu-west-1a
    private_subnet_1_cidr: 10.5.2.0/24
    private_subnet_1_az: eu-west-1b
    private_subnet_2_cidr: 10.5.3.0/24
    private_subnet_2_az: eu-west-1c

# Bastion Variables
    ec2_id: "ami-785db401"
    key_pair: "imagination-key"
    keypair_file: "imagination-key.pem"

# RDS Variables
    rds_user: root
    rds_pass: Default_Pass123!
    rds_instance_type: db.m1.small
    rds_size_gb: 15
    rds_parameter_engine: mysql5.6
    rds_instance_engine: 5.6.34
    rds_parameters:
      - { param: 'binlog_format', value: 'ROW' }
      - { param: 'general_log', value: '1' }

  pre_tasks:
  - name: install python
    raw: bash -c "test -e /usr/bin/python || (apt -qqy update && apt install -qqy python python-pip python3 python3-pip)"
    register: output
    changed_when: output.stdout != ""

  roles:
  # - keygen
  # - aws-network
  # - aws-bastion
  # - common
  # - aws-web
  - aws-rds
  # - mysql-client

- hosts: web

  roles:
  # - aws-bastion
  # - common
  # - aws-web
  # - mysql-client
