---
## This playbook deploys the whole application stack in this site.

- name: Deploy RDS Infratructure
  hosts: localhost
  connection: local
  # become: yes
  # remote_user: ubuntu
  gather_facts: false
  vars:

# Global AWS Variables
    region: eu-central-1
    vpc_name: dev

 # VPC Variables
    vpc_cidr: 10.5.0.0/16
    public_subnet_1_cidr: 10.5.0.0/24
    public_subnet_1_az: eu-central-1a
    private_subnet_1_cidr: 10.5.2.0/24
    private_subnet_1_az: eu-central-1b
    private_subnet_2_cidr: 10.5.3.0/24
    private_subnet_2_az: eu-central-1c

# Bastion Variables
    ami_id: "ami-1e339e71"
    keypair_name: "hosty-key"

# RDS Variables
    rds_user: root
    rds_pass: Default_Pass123!
    rds_instance_type: db.t2.small
    rds_size_gb: 15
    rds_parameter_engine: mysql5.6
    rds_instance_engine: 5.6.35
    rds_parameters:
      - { param: 'binlog_format', value: 'ROW' }
      - { param: 'general_log', value: '1' }

  roles:
  # - keygen
   - vpc
   # - bastion
   # - web
   # - rds
   # - nat
   # - common

# - hosts: bastion
#   become: yes
#
#   # pre_tasks:
#   #   - name: Update apt cache if needed.
#   #     shell: apt-get update && apt-get clean
#
#   # pre_tasks:
#   #   - name: install python
#   #     raw: bash -c "test -e /usr/bin/python || (apt -qqy update && apt install -qqy python python-pip python3 python3-pip)"
#   #     register: output
#   #     changed_when: output.stdout != ""
#
#   roles:
# #   # - bastion
#   - common
#   - mysql-client
#   # - { role: zerodeth.mysql-client, become: yes }

# - hosts: web
#   become: yes
# # #
# #   pre_tasks:
# #     - name: Update apt cache if needed.
# #       shell: apt-get update && apt-get clean
# #
#   roles:
#   - common
#   - mysql-client
#
