---
## This playbook deploys the whole application stack in this site.

- name: Deploy RDS Infratructure
  hosts: localhost
  connection: local
  gather_facts: false
  vars:

# Global AWS Variables
    region: eu-west-2
    vpc_name: dev

 # VPC Variables
    vpc_cidr: 10.5.0.0/16
    public_subnet_1_cidr: 10.5.0.0/24
    public_subnet_1_az: eu-west-2a
    public_subnet_2_cidr: 10.5.1.0/24
    public_subnet_2_az: eu-west-2b
    private_subnet_1_cidr: 10.5.2.0/24
    private_subnet_1_az: eu-west-2a
    private_subnet_2_cidr: 10.5.3.0/24
    private_subnet_2_az: eu-west-2b

# Bastion Variables (Ubuntu 16.04)
    ami_id: "ami-996372fd"  #eu-west-2
    # ami_id: "ami-1e339e71"  #eu-central-1
    keypair_name: "hostykey"

# RDS Variables
    rds_user: root
    rds_pass: Default_Pass123!
    rds_instance_type: db.t2.small
    rds_size_gb: 15
    rds_parameter_engine: mysql5.6
    rds_instance_engine: 5.6.35
    rds_parameters:
      - { param: 'binlog_format', value: 'ROW' }
      - { param: 'general_log', value: '1' }

  roles:
  - vpc
  - bastion
  - natclient
  - rds

# - hosts: natclient
#   become: yes
#
#   roles:
#   - common
#   - mysql-client
