---
- name: Deploy RDS Infratructure
  hosts: localhost
  connection: local
  gather_facts: false
  vars:

# Global AWS Variables
    region: eu-west-2
    aws_network_name: dev

# VPC Variables
    vpc_cidr: 10.4.0.0/16
    public_subnet_cidr: 10.4.0.0/24
    public_subnet_az: eu-west-2a
    private_subnet_1_cidr: 10.4.1.0/24
    private_subnet_1_az: eu-west-2b
    private_subnet_2_cidr: 10.4.2.0/24
    private_subnet_2_az: eu-west-2c

# Bastion Variables
    ec2_id: "ami-996372fd"
    key_pair: "imagination-key"

# RDS Variables
    rds_user: root
    rds_pass: Default_Pass123!
    rds_instance_type: db.m1.small
    rds_size_gb: 15
    rds_parameter_engine: mysql5.6
    rds_instance_engine: 5.6.34
    rds_parameters:
      - { param: 'binlog_format', value: 'ROW' }
      - { param: 'general_log', value: '1' }

  roles:
  - common
  - aws-network
  - aws-bastion
  - aws-rds
