private1---
# # tasks file for mysql-client
- name: "Get Private Subnet ID"
  ec2_vpc_subnet_facts:
    region: "{{ region }}"
    filters:
      "tag:Name": "{{ aws_network_name }}-private1"
  register: subnet_private1

  - name: Subnet ID
    debug:
      var: private_subnet['subnets'][0]['id']

    - name: Get web SG ID
      ec2_group_facts:
        region: "{{ region }}"
        filters:
          group-name: "{{ aws_network_name }}-web"
      register: web_sg

    - name: Web SG ID
      debug:
        var: web_sg['security_groups'][0]['group_id']

    - name: Create Web
      ec2:
        region: "{{ region }}"
        key_name: "{{ key_pair }}"
        group_id: "{{ web_sg['security_groups'][0]['group_id'] }}"
        instance_type: t2.micro
        image: "{{ ec2_id }}"
        wait: yes
        wait_timeout: 500
        exact_count: 1
        instance_tags:
          Name: "{{ aws_network_name }}-web"
          Environment: Dev
        count_tag:
          Name: "{{ aws_network_name }}-web"
          Environment: Dev
        vpc_subnet_id: "{{ private_subnet['subnets'][0]['id'] }}"
        assign_public_ip: no
      register: web_facts

    - debug: "var=web_facts"

    - name: Capture Web Private IP
      set_fact:
        web_private_ip: "{{ web_facts['instances'][0]['private_ip'] }}"
      when: web_facts['instances'] | length > 0

    - name: Capture Web Private IP
      set_fact:
        web_private_ip: "{{ web_facts['tagged_instances'][0]['private_ip'] }}"
      when: web_facts['tagged_instances'] | length > 0

##    - name: Add Web to hosts file
##      shell: "echo 'web ansible_host={{ web_public_ip }} ansible_user=ubuntu' >> {{ host_path }};echo '' >> {{ host_path }}"
