- name: Install MySQL packages
   apt: pkg={{item}} state=installed
   with_items:
     - bundler
     - mysql-client-core-5.6
     - libmysqlclient-dev
     - python-mysqldb
     - mysql-client
     - build-essential
- name: Remove the MySQL test database
   action: mysql_db db=test state=absent


- name: Create global my.cnf
   template: src=etc.my.cnf dest=/etc/mysql/my.cnf


- name: Add deploy DB user and allow access to news_* databases
   mysql_user: name={{user}} password={{password}} host="%" priv=db1.*:ALL/db2.*:ALL,GRANT state=present


- name: Set root password
   mysql_user: name=root password={{password}} host="{{item}}" priv=*.*:ALL,GRANT state=present
   with_items:
     - "{{ansible_hostname}}"
     - 127.0.0.1
     - ::1
     - localhost


- name: Create local my.cnf for root user
   template: src=my.cnf dest=/root/.my.cnf owner=root mode=0600


- name: Restart the MySQL service
   action: service name=mysql state=restarted enabled=true
