---
- name: create key pair
  ec2_key:
    region: "{{ region }}"
    name: "{{ key_pair }}"
  register: keypair

- name: write to local file
  copy: content="{{ keypair.key.private_key }}" dest="~/.ssh/{{ keypair_file }}.pem" mode=0600
  when: keypair.changed
