---
# # tasks file for web
- name: "Get Public Subnet ID"
  ec2_vpc_subnet_facts:
    region: "{{ region }}"
    filters:
      "tag:Name": "{{ vpc_name }}-public1"
  register: public_subnet_1

- name: Subnet ID
  debug:
    var: public_subnet_1['subnets'][0]['id']

- name: Get web SG ID
  ec2_group_facts:
    region: "{{ region }}"
    filters:
      group-name: "{{ vpc_name }}-web"
  register: web_sg

- name: Web SG ID
  debug:
    var: web_sg['security_groups'][0]['group_id']

- name: Create Web
  ec2:
    region: "{{ region }}"
    key_name: "{{ keypair_name }}"
    group_id: "{{ web_sg['security_groups'][0]['group_id'] }}"
    instance_type: t2.micro
    image: "{{ ami_id }}"
    wait: yes
    wait_timeout: 500
    exact_count: 1
    instance_tags:
      Name: "{{ vpc_name }}-web"
      Environment: Dev
    count_tag:
      Name: "{{ vpc_name }}-web"
      Environment: Dev
    vpc_subnet_id: "{{ public_subnet_1['subnets'][0]['id'] }}"
    assign_public_ip: yes
  register: web_facts

- debug: "var=web_facts"

- name: Capture Web Public IP
  set_fact:
    web_public_ip: "{{ web_facts['instances'][0]['public_ip'] }}"
  when: web_facts['instances'] | length > 0

- name: Capture Web Public IP
  set_fact:
    web_public_ip: "{{ web_facts['tagged_instances'][0]['public_ip'] }}"
  when: web_facts['tagged_instances'] | length > 0

# - name: Add Web to hosts file
#   shell: "echo 'web ansible_host={{ web_public_ip }} ansible_user=ubuntu' >> {{ host_path }};echo '' >> {{ host_path }}"
