---
- { include: debian.yml, become: yes }
- { include: ntp.yml, become: yes }

# - name: set timezone to Europe/London
#   timezone:
#     name: Europe/London

- name: get the current date and time
  shell: date
  register: d

- name: print the current date and time
  debug: var=d.stdout
