---
- hosts: localhost
  connection: local
  gather_facts: no
  vars:
    region: eu-central-1
    keypair_name: hosty-key
  tasks:
    - name: create key pair
      ec2_key:
        region: "{{ region }}"
        name: "{{ keypair_name }}"
      register: keypair

    - name: write to file
      copy: content="{{ keypair.key.private_key }}" dest="~/.ssh/{{ keypair_name }}.pem" mode=0600
      when: keypair.changed
